### ISSUE TITLE
Import error!

### ISSUE THREAD

**Issue by Rpersie** [kamo-naoyuki/pytorch_complex#1]
Hi kamo-naoyuki,
Thanks for your code! I have successfully installed the pytorch_complex. But when I just "from torch_complex.tensor import ComplexTensor", it have the errors "f'The first arg must be torch.Tensor'".  Can you give me some ideas ? Thank you !

**Comment by kamo-naoyuki** [comment]
Do you mean that you met an error when instantiation of ComplexTensor?

https://github.com/kamo-naoyuki/pytorch_complex/blob/ca2df702ccf284a129273f8d2354973cbe3ffdfd/torch_complex/tensor.py#L25-L29

The message may come from __init__ and maybe your usage is incorrect.

e.g.

```python
from torch_complex.tensor import ComplexTensor
not_tensor_object = 2
ComplexTensor(not_tensor_object)
```

**Comment by Rpersie** [comment]
Thank you! 
I just type the " from torch_complex.tensor import ComplexTensor", it has the error !

>>> from torch_complex.tensor import ComplexTensor
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nobackup/f1/asr/wulong/espnet-me2e/espnet-frontend/tools/pytorch_complex-master/torch_complex/tensor.py", line 27
    f'The first arg must be torch.Tensor'
                                        ^
SyntaxError: invalid syntax

**Comment by kamo-naoyuki** [comment]
I see. This module requires python>=3.6 because of fstring syntax.

**Comment by Rpersie** [comment]
oh, thank you very much ! I do not expect it is so strict with  the python version. My python is 3.5
